### PR TITLE
encoding fix for patch

### PR DESCRIPTION
**Pull request by noxifoxi**
Somehow the patch was in utf-16 and that's just garbage for the patch program (that's probably the reason why the v1.20.6 build failed)

I've converted the file to utf-8 and it should work now (after the conversion applying the patch worked for me).

### CODE REVIEW

**Comment by LukeChannings** [comment]
Let's give it a try!

**Comment by noxifoxi** [comment]
I pray that it works, building with this patch works for me on x86_64.
I have no clue why patch (or git?) decided utf-16 is a good idea.

**Comment by LukeChannings** [comment]
@noxifoxi Seems to be working, thanks! I wasn't looking forward to debugging this 😂

**Comment by LukeChannings** [comment]
```
~$ ./deno upgrade
Looking up latest version
Found latest version 1.21.0
Checking https://github.com/LukeChannings/deno-arm64/releases/download/v1.21.0/deno-linux-arm64.zip
32.1 MiB / 32.1 MiB (100.0%)
Deno is upgrading to version 1.21.0
Archive:  /tmp/.tmpcXVdQc/deno.zip
  inflating: deno
Upgraded successfully
```

Success 🥳

**Pull request merged**
