### PR TITLE
feat: add install script

### PR DESCRIPTION
**Pull request by xhyrom**

### CODE REVIEW

**Comment by noxifoxi** [comment]
why? 🤷🏻‍♀️ 
also: https://github.com/noxifoxi/deno_install-arm64

**Comment by xhyrom** [comment]
why not

**Comment by LukeChannings** [comment]
This is just a copy of Deno's install script with the repo URL updated to `lukechannings/deno-arm64`.

Firstly, this script won't actually work, because I don't publish `deno-linux-amd64.zip` files, and secondly for this to be useful:

1. It should check the architecture the script is running under
2. If being run under x86, it should download the official Deno binary,
3. if it's run under an arm64 host, it should download my binary,
4. if it's being run under a 32-bit ARM host it should give an informative error

This seems like a low effort PR that isn't worth merging, sorry!

**Comment by xhyrom** [comment]
I could just fix this issues but there is https://github.com/noxifoxi/deno_install-arm64 so 👍

**Pull request closed without merging**
